In [25]:
import requests
import json
from prettytable import PrettyTable
import pandas as pd

In [140]:
headers = {'Content-type': 'application/json'}
data_us = json.dumps({"seriesid": ['LNS14000000'],"startyear":"2012", "endyear":"2021"})
p_us = requests.post('https://api.bls.gov/publicAPI/v2/timeseries/data/', data=data_us, headers=headers)
json_data_us = json.loads(p_us.text)

for series in json_data_us['Results']['series']:
    x=prettytable.PrettyTable(["series id","year","period","periodName","value","footnotes"])
    seriesId = series['seriesID']
    for item in series['data']:
        year = item['year']
        period = item['period']
        periodName = item['periodName']
        value = item['value']
        footnotes=""
        for footnote in item['footnotes']:
            if footnote:
                footnotes = footnotes + footnote['text'] + ','
        if 'M01' <= period <= 'M12':
            x.add_row([seriesId,year,period,periodName,value,footnotes[0:-1]])
    output = open(seriesId + '.csv','w')
    output.write (x.get_string())
    output.close()
    
    #Storing JSON output in a file which would be downloaded in the desktop

In [141]:
json_data_us

{'status': 'REQUEST_SUCCEEDED',
 'responseTime': 204,
 'message': [],
 'Results': {'series': [{'seriesID': 'LNS14000000',
    'data': [{'year': '2021',
      'period': 'M02',
      'periodName': 'February',
      'latest': 'true',
      'value': '6.2',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M01',
      'periodName': 'January',
      'value': '6.3',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M12',
      'periodName': 'December',
      'value': '6.7',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M11',
      'periodName': 'November',
      'value': '6.7',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M10',
      'periodName': 'October',
      'value': '6.9',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M09',
      'periodName': 'September',
      'value': '7.8',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M08',
      'periodName': 'August',
      'value': '8.4',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M07',
      'periodName': 'July',
      'value': '10.2',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M06',
      'periodName': 'June',
      'value': '11.1',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M05',
      'periodName': 'May',
      'value': '13.3',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M04',
      'periodName': 'April',
      'value': '14.8',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M03',
      'periodName': 'March',
      'value': '4.4',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M02',
      'periodName': 'February',
      'value': '3.5',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M01',
      'periodName': 'January',
      'value': '3.5',
      'footnotes': [{}]},
     {'year': '2019',
      'period': 'M12',
      'periodName': 'December',
      'value': '3.6',
      'footnotes': [{}]},
     {'year': '2019',
      'period': 'M11',
      'periodName': 'November',
      'value': '3.6',
      'footnotes': [{}]},
     {'year': '2019',
      'period': 'M10',
      'periodName': 'October',
      'value': '3.6',
      'footnotes': [{}]},
     {'year': '2019',
      'period': 'M09',
      'periodName': 'September',
      'value': '3.5',
      'footnotes': [{}]},
     {'year': '2019',
      'period': 'M08',
      'periodName': 'August',
      'value': '3.7',
      'footnotes': [{}]},
     {'year': '2019',
      'period': 'M07',
      'periodName': 'July',
      'value': '3.6',
      'footnotes': [{}]},
     {'year': '2019',
      'period': 'M06',
      'periodName': 'June',
      'value': '3.6',
      'footnotes': [{}]},
     {'year': '2019',
      'period': 'M05',
      'periodName': 'May',
      'value': '3.7',
      'footnotes': [{}]},
     {'year': '2019',
      'period': 'M04',
      'periodName': 'April',
      'value': '3.7',
      'footnotes': [{}]},
     {'year': '2019',
      'period': 'M03',
      'periodName': 'March',
      'value': '3.8',
      'footnotes': [{}]},
     {'year': '2019',
      'period': 'M02',
      'periodName': 'February',
      'value': '3.8',
      'footnotes': [{}]},
     {'year': '2019',
      'period': 'M01',
      'periodName': 'January',
      'value': '4.0',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M12',
      'periodName': 'December',
      'value': '3.9',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M11',
      'periodName': 'November',
      'value': '3.8',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M10',
      'periodName': 'October',
      'value': '3.8',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M09',
      'periodName': 'September',
      'value': '3.7',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M08',
      'periodName': 'August',
      'value': '3.8',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M07',
      'periodName': 'July',
      'value': '3.8',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M06',
      'periodName': 'June',
      'value': '4.0',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M05',
      'periodName': 'May',
      'value': '3.8',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M04',
      'periodName': 'April',
      'value': '4.0',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M03',
      'periodName': 'March',
      'value': '4.0',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M02',
      'periodName': 'February',
      'value': '4.1',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M01',
      'periodName': 'January',
      'value': '4.0',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M12',
      'periodName': 'December',
      'value': '4.1',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M11',
      'periodName': 'November',
      'value': '4.2',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M10',
      'periodName': 'October',
      'value': '4.1',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M09',
      'periodName': 'September',
      'value': '4.2',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M08',
      'periodName': 'August',
      'value': '4.4',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M07',
      'periodName': 'July',
      'value': '4.3',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M06',
      'periodName': 'June',
      'value': '4.3',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M05',
      'periodName': 'May',
      'value': '4.4',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M04',
      'periodName': 'April',
      'value': '4.5',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M03',
      'periodName': 'March',
      'value': '4.4',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M02',
      'periodName': 'February',
      'value': '4.6',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M01',
      'periodName': 'January',
      'value': '4.7',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M12',
      'periodName': 'December',
      'value': '4.7',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M11',
      'periodName': 'November',
      'value': '4.7',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M10',
      'periodName': 'October',
      'value': '4.9',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M09',
      'periodName': 'September',
      'value': '5.0',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M08',
      'periodName': 'August',
      'value': '4.9',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M07',
      'periodName': 'July',
      'value': '4.8',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M06',
      'periodName': 'June',
      'value': '4.9',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M05',
      'periodName': 'May',
      'value': '4.8',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M04',
      'periodName': 'April',
      'value': '5.1',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M03',
      'periodName': 'March',
      'value': '5.0',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M02',
      'periodName': 'February',
      'value': '4.9',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M01',
      'periodName': 'January',
      'value': '4.8',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M12',
      'periodName': 'December',
      'value': '5.0',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M11',
      'periodName': 'November',
      'value': '5.1',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M10',
      'periodName': 'October',
      'value': '5.0',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M09',
      'periodName': 'September',
      'value': '5.0',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M08',
      'periodName': 'August',
      'value': '5.1',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M07',
      'periodName': 'July',
      'value': '5.2',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M06',
      'periodName': 'June',
      'value': '5.3',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M05',
      'periodName': 'May',
      'value': '5.6',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M04',
      'periodName': 'April',
      'value': '5.4',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M03',
      'periodName': 'March',
      'value': '5.4',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M02',
      'periodName': 'February',
      'value': '5.5',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M01',
      'periodName': 'January',
      'value': '5.7',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M12',
      'periodName': 'December',
      'value': '5.6',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M11',
      'periodName': 'November',
      'value': '5.8',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M10',
      'periodName': 'October',
      'value': '5.7',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M09',
      'periodName': 'September',
      'value': '5.9',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M08',
      'periodName': 'August',
      'value': '6.1',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M07',
      'periodName': 'July',
      'value': '6.2',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M06',
      'periodName': 'June',
      'value': '6.1',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M05',
      'periodName': 'May',
      'value': '6.3',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M04',
      'periodName': 'April',
      'value': '6.2',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M03',
      'periodName': 'March',
      'value': '6.7',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M02',
      'periodName': 'February',
      'value': '6.7',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M01',
      'periodName': 'January',
      'value': '6.6',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M12',
      'periodName': 'December',
      'value': '6.7',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M11',
      'periodName': 'November',
      'value': '6.9',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M10',
      'periodName': 'October',
      'value': '7.2',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M09',
      'periodName': 'September',
      'value': '7.2',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M08',
      'periodName': 'August',
      'value': '7.2',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M07',
      'periodName': 'July',
      'value': '7.3',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M06',
      'periodName': 'June',
      'value': '7.5',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M05',
      'periodName': 'May',
      'value': '7.5',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M04',
      'periodName': 'April',
      'value': '7.6',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M03',
      'periodName': 'March',
      'value': '7.5',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M02',
      'periodName': 'February',
      'value': '7.7',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M01',
      'periodName': 'January',
      'value': '8.0',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M12',
      'periodName': 'December',
      'value': '7.9',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M11',
      'periodName': 'November',
      'value': '7.7',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M10',
      'periodName': 'October',
      'value': '7.8',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M09',
      'periodName': 'September',
      'value': '7.8',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M08',
      'periodName': 'August',
      'value': '8.1',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M07',
      'periodName': 'July',
      'value': '8.2',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M06',
      'periodName': 'June',
      'value': '8.2',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M05',
      'periodName': 'May',
      'value': '8.2',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M04',
      'periodName': 'April',
      'value': '8.2',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M03',
      'periodName': 'March',
      'value': '8.2',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M02',
      'periodName': 'February',
      'value': '8.3',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M01',
      'periodName': 'January',
      'value': '8.3',
      'footnotes': [{}]}]}]}}

In [142]:
#Loading Data in Dataframe

df_us = pd.json_normalize(json_data_us['Results']['series'],record_path=['data'])
df_us

     year period periodName latest value footnotes
0    2021    M02   February   true   6.2      [{}]
1    2021    M01    January    NaN   6.3      [{}]
2    2020    M12   December    NaN   6.7      [{}]
3    2020    M11   November    NaN   6.7      [{}]
4    2020    M10    October    NaN   6.9      [{}]
..    ...    ...        ...    ...   ...       ...
105  2012    M05        May    NaN   8.2      [{}]
106  2012    M04      April    NaN   8.2      [{}]
107  2012    M03      March    NaN   8.2      [{}]
108  2012    M02   February    NaN   8.3      [{}]
109  2012    M01    January    NaN   8.3      [{}]

[110 rows x 6 columns]

In [143]:
df_us['value']=df_us['value'].astype(float)
df_us.dtypes

year           object
period         object
periodName     object
latest         object
value         float64
footnotes      object
dtype: object

In [181]:
df_us_mean = round(df_us.groupby(by='year',as_index=False).mean(),1)
df_us_mean = df_us_mean.sort_values(by='year', ascending= False)
df_us_mean

   year  value
9  2021    6.2
8  2020    8.1
7  2019    3.7
6  2018    3.9
5  2017    4.4
4  2016    4.9
3  2015    5.3
2  2014    6.2
1  2013    7.4
0  2012    8.1

In [182]:
#Exporting monthly and yearly data in two separte sheets

with pd.ExcelWriter('US Unemployment Rate.xlsx') as writer:
    df_us.to_excel(writer, sheet_name='Monthly - Unemployment Rate',index=False)
    df_us_mean.to_excel(writer, sheet_name='Yearly - Unemployment Rate', index= False)

In [173]:
headers = {'Content-type': 'application/json'}
data = json.dumps({"seriesid": ['LAUMT124530000000003'],"startyear":"2012", "endyear":"2021"})
p = requests.post('https://api.bls.gov/publicAPI/v2/timeseries/data/', data=data, headers=headers)
json_data = json.loads(p.text)

for series in json_data['Results']['series']:
    x=prettytable.PrettyTable(["series id","year","period","periodName","value","footnotes"])
    seriesId = series['seriesID']
    for item in series['data']:
        year = item['year']
        period = item['period']
        periodName = item['periodName']
        value = item['value']
        footnotes=""
        for footnote in item['footnotes']:
            if footnote:
                footnotes = footnotes + footnote['text'] + ','
        if 'M01' <= period <= 'M12':
            x.add_row([seriesId,year,period,periodName,value,footnotes[0:-1]])
    output = open(seriesId + '.csv','w')
    output.write (x.get_string())
    output.close()

In [174]:
json_data

{'status': 'REQUEST_SUCCEEDED',
 'responseTime': 209,
 'message': [],
 'Results': {'series': [{'seriesID': 'LAUMT124530000000003',
    'data': [{'year': '2021',
      'period': 'M01',
      'periodName': 'January',
      'latest': 'true',
      'value': '4.6',
      'footnotes': [{'code': 'P', 'text': 'Preliminary.'}]},
     {'year': '2020',
      'period': 'M12',
      'periodName': 'December',
      'value': '5.2',
      'footnotes': [{'code': 'P', 'text': 'Preliminary.'}]},
     {'year': '2020',
      'period': 'M11',
      'periodName': 'November',
      'value': '5.5',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M10',
      'periodName': 'October',
      'value': '5.4',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M09',
      'periodName': 'September',
      'value': '5.7',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M08',
      'periodName': 'August',
      'value': '6.7',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M07',
      'periodName': 'July',
      'value': '10.2',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M06',
      'periodName': 'June',
      'value': '9.0',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M05',
      'periodName': 'May',
      'value': '12.2',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M04',
      'periodName': 'April',
      'value': '13.2',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M03',
      'periodName': 'March',
      'value': '4.3',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M02',
      'periodName': 'February',
      'value': '3.0',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M01',
      'periodName': 'January',
      'value': '3.1',
      'footnotes': [{}]},
     {'year': '2019',
      'period': 'M12',
      'periodName': 'December',
      'value': '2.7',
      'footnotes': [{}]},
     {'year': '2019',
      'period': 'M11',
      'periodName': 'November',
      'value': '2.8',
      'footnotes': [{}]},
     {'year': '2019',
      'period': 'M10',
      'periodName': 'October',
      'value': '2.9',
      'footnotes': [{}]},
     {'year': '2019',
      'period': 'M09',
      'periodName': 'September',
      'value': '2.9',
      'footnotes': [{}]},
     {'year': '2019',
      'period': 'M08',
      'periodName': 'August',
      'value': '3.3',
      'footnotes': [{}]},
     {'year': '2019',
      'period': 'M07',
      'periodName': 'July',
      'value': '3.4',
      'footnotes': [{}]},
     {'year': '2019',
      'period': 'M06',
      'periodName': 'June',
      'value': '3.4',
      'footnotes': [{}]},
     {'year': '2019',
      'period': 'M05',
      'periodName': 'May',
      'value': '3.1',
      'footnotes': [{}]},
     {'year': '2019',
      'period': 'M04',
      'periodName': 'April',
      'value': '3.0',
      'footnotes': [{}]},
     {'year': '2019',
      'period': 'M03',
      'periodName': 'March',
      'value': '3.3',
      'footnotes': [{}]},
     {'year': '2019',
      'period': 'M02',
      'periodName': 'February',
      'value': '3.4',
      'footnotes': [{}]},
     {'year': '2019',
      'period': 'M01',
      'periodName': 'January',
      'value': '3.8',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M12',
      'periodName': 'December',
      'value': '3.4',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M11',
      'periodName': 'November',
      'value': '3.3',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M10',
      'periodName': 'October',
      'value': '3.3',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M09',
      'periodName': 'September',
      'value': '3.3',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M08',
      'periodName': 'August',
      'value': '3.6',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M07',
      'periodName': 'July',
      'value': '3.7',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M06',
      'periodName': 'June',
      'value': '3.8',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M05',
      'periodName': 'May',
      'value': '3.4',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M04',
      'periodName': 'April',
      'value': '3.4',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M03',
      'periodName': 'March',
      'value': '3.6',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M02',
      'periodName': 'February',
      'value': '3.8',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M01',
      'periodName': 'January',
      'value': '4.1',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M12',
      'periodName': 'December',
      'value': '3.7',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M11',
      'periodName': 'November',
      'value': '3.9',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M10',
      'periodName': 'October',
      'value': '3.8',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M09',
      'periodName': 'September',
      'value': '3.9',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M08',
      'periodName': 'August',
      'value': '4.2',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M07',
      'periodName': 'July',
      'value': '4.2',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M06',
      'periodName': 'June',
      'value': '4.2',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M05',
      'periodName': 'May',
      'value': '3.9',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M04',
      'periodName': 'April',
      'value': '3.8',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M03',
      'periodName': 'March',
      'value': '4.0',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M02',
      'periodName': 'February',
      'value': '4.3',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M01',
      'periodName': 'January',
      'value': '4.7',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M12',
      'periodName': 'December',
      'value': '4.3',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M11',
      'periodName': 'November',
      'value': '4.4',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M10',
      'periodName': 'October',
      'value': '4.5',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M09',
      'periodName': 'September',
      'value': '4.7',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M08',
      'periodName': 'August',
      'value': '4.7',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M07',
      'periodName': 'July',
      'value': '4.8',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M06',
      'periodName': 'June',
      'value': '4.8',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M05',
      'periodName': 'May',
      'value': '4.3',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M04',
      'periodName': 'April',
      'value': '4.4',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M03',
      'periodName': 'March',
      'value': '4.5',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M02',
      'periodName': 'February',
      'value': '4.5',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M01',
      'periodName': 'January',
      'value': '4.9',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M12',
      'periodName': 'December',
      'value': '4.7',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M11',
      'periodName': 'November',
      'value': '4.9',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M10',
      'periodName': 'October',
      'value': '4.9',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M09',
      'periodName': 'September',
      'value': '5.0',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M08',
      'periodName': 'August',
      'value': '5.2',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M07',
      'periodName': 'July',
      'value': '5.5',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M06',
      'periodName': 'June',
      'value': '5.4',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M05',
      'periodName': 'May',
      'value': '5.3',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M04',
      'periodName': 'April',
      'value': '5.1',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M03',
      'periodName': 'March',
      'value': '5.2',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M02',
      'periodName': 'February',
      'value': '5.4',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M01',
      'periodName': 'January',
      'value': '5.9',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M12',
      'periodName': 'December',
      'value': '5.4',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M11',
      'periodName': 'November',
      'value': '5.8',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M10',
      'periodName': 'October',
      'value': '5.7',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M09',
      'periodName': 'September',
      'value': '5.9',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M08',
      'periodName': 'August',
      'value': '6.2',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M07',
      'periodName': 'July',
      'value': '6.3',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M06',
      'periodName': 'June',
      'value': '6.1',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M05',
      'periodName': 'May',
      'value': '6.0',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M04',
      'periodName': 'April',
      'value': '5.8',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M03',
      'periodName': 'March',
      'value': '6.2',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M02',
      'periodName': 'February',
      'value': '6.3',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M01',
      'periodName': 'January',
      'value': '6.5',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M12',
      'periodName': 'December',
      'value': '6.0',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M11',
      'periodName': 'November',
      'value': '6.3',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M10',
      'periodName': 'October',
      'value': '6.5',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M09',
      'periodName': 'September',
      'value': '6.6',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M08',
      'periodName': 'August',
      'value': '6.9',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M07',
      'periodName': 'July',
      'value': '7.1',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M06',
      'periodName': 'June',
      'value': '7.2',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M05',
      'periodName': 'May',
      'value': '6.8',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M04',
      'periodName': 'April',
      'value': '6.7',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M03',
      'periodName': 'March',
      'value': '6.9',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M02',
      'periodName': 'February',
      'value': '7.4',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M01',
      'periodName': 'January',
      'value': '8.0',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M12',
      'periodName': 'December',
      'value': '7.5',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M11',
      'periodName': 'November',
      'value': '7.5',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M10',
      'periodName': 'October',
      'value': '7.7',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M09',
      'periodName': 'September',
      'value': '7.9',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M08',
      'periodName': 'August',
      'value': '8.4',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M07',
      'periodName': 'July',
      'value': '8.7',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M06',
      'periodName': 'June',
      'value': '8.6',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M05',
      'periodName': 'May',
      'value': '8.2',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M04',
      'periodName': 'April',
      'value': '8.0',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M03',
      'periodName': 'March',
      'value': '8.3',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M02',
      'periodName': 'February',
      'value': '8.7',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M01',
      'periodName': 'January',
      'value': '9.0',
      'footnotes': [{}]}]}]}}

In [175]:
df = pd.json_normalize(json_data['Results']['series'],record_path=['data'])
df

,year,period,periodName,latest,value,footnotes
0,2021,M01,January,true,4.6,"[{'code': 'P', 'text': 'Preliminary.'}]"
1,2020,M12,December,NaN,5.2,"[{'code': 'P', 'text': 'Preliminary.'}]"
2,2020,M11,November,NaN,5.5,[{}]
3,2020,M10,October,NaN,5.4,[{}]
4,2020,M09,September,NaN,5.7,[{}]
...,...,...,...,...,...,...
104,2012,M05,May,NaN,8.2,[{}]
105,2012,M04,April,NaN,8.0,[{}]
106,2012,M03,March,NaN,8.3,[{}]
107,2012,M02,February,NaN,8.7,[{}]
108,2012,M01,January,NaN,9.0,[{}]

In [176]:
df['value']=df['value'].astype(float)
df.dtypes

year           object
period         object
periodName     object
latest         object
value         float64
footnotes      object
dtype: object

In [183]:
df_mean = round(df.groupby(by='year',as_index=False).mean(),1)
df_mean = df_mean.sort_values(by='year', ascending= False)
df_mean

   year  value
9  2021    4.6
8  2020    7.0
7  2019    3.2
6  2018    3.6
5  2017    4.0
4  2016    4.6
3  2015    5.2
2  2014    6.0
1  2013    6.9
0  2012    8.2

In [184]:
with pd.ExcelWriter('Tampa Unemployment Rate.xlsx') as writer:
    df.to_excel(writer, sheet_name='MOnthly - Unemployment Rate',index=False)
    df_mean.to_excel(writer, sheet_name='Yearly - Unemployment Rate',index=False)